import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter, NavLink, Routes, Route, Link } from 'react-router-dom';
import { DashboardPage } from './DashboardPage';
import { BooksPage } from './BooksPage';
import { AuthorsPage, CategoriesPage } from './CategoriesPage';
import { ReadersPage } from './ReadersPage';
import { CopiesPage } from './CopiesPage';
import { LoansPage } from './LoansPage';
import './styles.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><a className="skip" href="#main">Pular para o conteúdo</a><header><Link className="brand" to="/">▤ Biblioteca</Link><nav aria-label="Principal"><NavLink to="/" end>Visão geral</NavLink><NavLink to="/categories">Categorias</NavLink><NavLink to="/authors">Autores</NavLink><NavLink to="/books">Livros</NavLink><NavLink to="/readers">Leitores</NavLink><NavLink to="/copies">Exemplares</NavLink><NavLink to="/loans">Circulação</NavLink></nav><span className="local">Gestão local</span></header><main id="main"><Routes><Route path="/" element={<DashboardPage />} /><Route path="/categories" element={<CategoriesPage />} /><Route path="/authors" element={<AuthorsPage />} /><Route path="/books" element={<BooksPage />} /><Route path="/readers" element={<ReadersPage />} /><Route path="/copies" element={<CopiesPage />} /><Route path="/loans" element={<LoansPage />} /><Route path="*" element={<section><h1>Página não encontrada</h1><Link to="/">Voltar ao início</Link></section>} /></Routes></main><footer>Sistema de gestão da biblioteca · Projeto acadêmico</footer></BrowserRouter></React.StrictMode>);
